name: "Test Code"

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build --tag nuitka-test:latest .
      
      - name: Run Tests (Python)
        run: docker run --workdir /nuitka-test --env test_library="/nuitka-test/test_library.so" nuitka-test:latest ./nuitka-test.py
      
      - name: Run Tests (Compiled)
        run: docker run --workdir /nuitka-test --env test_library="/nuitka-test/test_library.so" nuitka-test:latest ./nuitka-test.bin
      
      - name: Check Dependencies
        run: docker run --workdir /nuitka-test nuitka-test:latest ldd /nuitka-test/nuitka-test.bin  | grep -q libpython; test $? -eq 1
