name: "Test Code"

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Image
        run: docker build --tag nuitka-test:latest .
      
      - name: Run Tests (Python)
        run: docker run --workdir /nuitka-test --env test_library="/nuitka-test/test_library.so" nuitka-test:latest ./nuitka-test.py
      
      - name: Run Tests (Compiled)
        run: docker run --workdir /nuitka-test --env test_library="/nuitka-test/test_library.so" nuitka-test:latest ./nuitka-test.bin
      
      - name: Check Dependencies
        run: |
          docker run --rm nuitka-test:latest cat /nuitka-test/nuitka-test.bin > ./nuitka-test.bin
          docker run --rm nuitka-test:latest cat /nuitka-test/test_library.so > ./test_library.so
          docker run --volume $PWD/test_library.so:/tmp/test_library.so --volume $PWD/nuitka-test.bin:/tmp/nuitka-test.bin --env test_library="/tmp/test_library.so" alpine:latest ls -la /tmp/
          
